{
  "seed": 1337,
  "experiment_name": "squad_demo",
  "data": {
    "dataset_id": "squad",
    "split_train": "train[:1%]",
    "split_eval": "validation[:1%]"
  },
  "retriever": {
    "type": "tfidf",
    "max_docs": 5
  },
  "reader": {
    "model_name": "distilbert-base-uncased",
    "epochs": 1,
    "batch_size": 8,
    "lr": 3e-05,
    "max_length": 384,
    "doc_stride": 128
  },
  "eval": {
    "abstain_threshold": 0.15
  },
  "outputs": {
    "run_dir": "runs/squad_demo",
    "results_json": "runs/squad_demo/results.json",
    "latex_table": "paper/results.tex",
    "fig_dir": "paper/figures"
  }
}